language: generic

matrix:
  include:
    - os: linux
      compiler: gcc

      sudo: required
      dist: trusty

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - gcc-5
            - g++-5
            - gcc-5-multilib
            - g++-5-multilib

      env:
        - COMPILER_NAME=gcc
        - CC=gcc-5
        - CXX=g++-5

      script:
        - ./build/nix/release.sh

    - os: windows

      script:
        - echo 1

notifications:
  email: trflynn89@gmail.com
