language: generic

matrix:
  include:
    - os: linux
      compiler: gcc

      sudo: required
      dist: trusty

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - gcc-5
            - g++-5
            - gcc-5-multilib
            - g++-5-multilib
      env:
        - COMPILER_NAME=gcc
        - CC=gcc-5
        - CXX=g++-5

      before_script:
        - sudo ln -s /usr/include/asm-generic /usr/include/asm

      script:
        - ./build/nix/release.sh

notifications:
  email: trflynn89@gmail.com
